# Config File:
train: C:\Projects\SMART_PARK\moc_parking_lot_datatset\train
val: C:\Projects\SMART_PARK\moc_parking_lot_datatset\val
test: C:\Projects\SMART_PARK\moc_parking_lot_datatset\test

nc: 2
names: ['vacant', 'occupied'] 